### ISSUE TITLE
Failed to get IB devices list: Function not implemented

### ISSUE THREAD

**Issue by bueryg** [WukLab/LITE#5]

**Comment by shinyehtsai** [comment]
Can you execute ibv_devinfo to get respected information?

**Comment by bueryg** [comment]
No, it also prints
Failed to get IB devices list:Function not implemented
Do I need to reinstall the RDMA drivers?

**Comment by shinyehtsai** [comment]
Actually, mgmt-server side doesn't really need to have very low-level requirement since it's a userspace program with regular verbs. And it doesn't require to use specific kernel version. You could try to use vanilla CentOS or Ubuntu for mgmt-server side. If you have a machine which can run IB-perftest or other related programs, it should be able to run mgmt-server.

**Comment by bueryg** [comment]
Could you please tell me the RDMA driver you used? The readme.md says LITE is not compatible with MLNX_OFED now.

**Comment by shinyehtsai** [comment]
mgmt-server's code have been tested in kernel 3.10.97, and 3.11.1 (with original linux inbox driver).

mgmt-server's code lies in userspace. Therefore, as long as your machine can run RDMA without issues, **you should be able run mgmt-server directly**. (we have also tested mgmt-server on kernel 4.4.84 with MLNX_OFED and Cent7.2 with linux inbox driver). 

However, LITE's kernel code (core directory) requires low-level function call inside driver, and MLNX_OFED replaces this hook with their own function. Therefore, we explicitly state that **LITE's code can't work with MLNX_OFED.**
